# Generated by Django 5.2.7 on 2025-10-30 02:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-is_current', '-end_date'], 'verbose_name': '教育经历', 'verbose_name_plural': '教育经历'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': '用户技能', 'verbose_name_plural': '用户技能'},
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(db_index=True, max_length=100, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False, verbose_name='当前在读'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='精选'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='公开'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True, verbose_name='项目链接'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies_used',
            field=models.TextField(help_text='Comma-separated list of technologies', verbose_name='使用技术'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(db_index=True, max_length=50, verbose_name='技能分类'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, verbose_name='技能描述'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='技能名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='邮件通知启用'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='身份已验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='手机已验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最后登录位置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_emails_enabled',
            field=models.BooleanField(default=False, verbose_name='营销邮件启用'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Chinese mainland mobile number', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completion_percentage',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='资料完成度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('suspended', '已暂停'), ('pending_verification', '待验证')], db_index=True, default='active', max_length=30, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', '客户'), ('freelancer', '自由职业者'), ('admin', '管理员')], db_index=True, max_length=20, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid WeChat ID format', regex='^[a-zA-Z][a-zA-Z0-9_-]{5,19}$')], verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='公司注册号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='公司网站'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='China', max_length=50, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub链接'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='时薪'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn链接'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='作品集链接'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(default='zh-hans', max_length=10, verbose_name='首选语言'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', '公开'), ('private', '私有'), ('unlisted', '不公开')], default='public', max_length=20, verbose_name='资料可见性'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('beijing', 'Beijing'), ('shanghai', 'Shanghai'), ('guangdong', 'Guangdong'), ('zhejiang', 'Zhejiang'), ('jiangsu', 'Jiangsu'), ('sichuan', 'Sichuan'), ('hubei', 'Hubei'), ('hunan', 'Hunan'), ('fujian', 'Fujian'), ('shandong', 'Shandong'), ('henan', 'Henan'), ('anhui', 'Anhui'), ('chongqing', 'Chongqing'), ('tianjin', 'Tianjin'), ('liaoning', 'Liaoning'), ('jilin', 'Jilin'), ('heilongjiang', 'Heilongjiang'), ('shaanxi', 'Shaanxi'), ('shanxi', 'Shanxi'), ('hebei', 'Hebei'), ('xinjiang', 'Xinjiang'), ('tibet', 'Tibet'), ('qinghai', 'Qinghai'), ('gansu', 'Gansu'), ('ningxia', 'Ningxia'), ('yunnan', 'Yunnan'), ('guizhou', 'Guizhou'), ('guangxi', 'Guangxi'), ('hainan', 'Hainan'), ('inner_mongolia', 'Inner Mongolia'), ('taiwan', 'Taiwan'), ('hong_kong', 'Hong Kong'), ('macau', 'Macau')], max_length=50, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='工作经验年限'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='proficiency_level',
            field=models.IntegerField(db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='熟练程度'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_users', to='accounts.skill', verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='经验年限'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='公司所在地'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, to='accounts.skill', verbose_name='使用技能'),
        ),
    ]
