# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_education_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies_used',
            field=models.TextField(help_text='Comma-separated list of technologies'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
