# Generated by Django 5.2.7 on 2025-11-03 01:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_delivery_options_alter_order_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrow',
            options={'verbose_name': '托管账户', 'verbose_name_plural': '托管账户'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': '支付方式', 'verbose_name_plural': '支付方式'},
        ),
        migrations.AlterModelOptions(
            name='paymentrefund',
            options={'ordering': ['-created_at'], 'verbose_name': '支付退款', 'verbose_name_plural': '支付退款'},
        ),
        migrations.AlterModelOptions(
            name='paymentstat',
            options={'ordering': ['-date'], 'verbose_name': '支付统计', 'verbose_name_plural': '支付统计'},
        ),
        migrations.AlterModelOptions(
            name='payoutbatch',
            options={'ordering': ['-created_at'], 'verbose_name': '派发批次', 'verbose_name_plural': '派发批次'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': '交易', 'verbose_name_plural': '交易'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': '钱包', 'verbose_name_plural': '钱包'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': '提现', 'verbose_name_plural': '提现'},
        ),
        migrations.AlterField(
            model_name='escrow',
            name='auto_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自动释放日期'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_client', to=settings.AUTH_USER_MODEL, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_as_freelancer', to=settings.AUTH_USER_MODEL, verbose_name='自由职业者'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='freelancer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='自由职业者金额'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资金时间'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='funding_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_escrows', to='payments.transaction', verbose_name='资金交易'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='is_manual_release_required',
            field=models.BooleanField(db_index=True, default=False, verbose_name='需要手动释放'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='平台费用'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款时间'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='release_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_escrows', to='payments.transaction', verbose_name='释放交易'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='释放时间'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('funded', '已资金'), ('released', '已释放'), ('refunded', '已退款'), ('disputed', '纠纷中')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='账户名'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(max_length=100, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='encrypted_data',
            field=models.TextField(blank=True, verbose_name='加密数据'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_card', '银行卡'), ('credit_card', '信用卡')], max_length=20, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(blank=True, max_length=50, verbose_name='提供商'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='CNY', max_length=3, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='净金额'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('unionpay', '银联'), ('wallet', '平台钱包'), ('stripe', 'Stripe')], db_index=True, max_length=20, verbose_name='提供商'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='提供商响应'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='提供商交易号'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('reversed', '已撤销')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='交易号'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', '存款'), ('withdrawal', '提现'), ('payment', '支付'), ('refund', '退款'), ('payout', '派发'), ('fee', '平台费用'), ('bonus', '奖励'), ('penalty', '罚金')], db_index=True, max_length=20, verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen_balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结余额'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总收入'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总支出'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdrawal_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='提现账户'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdrawal_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdrawal_method',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_transfer', '银行转账')], default='alipay', max_length=20, verbose_name='提现方式'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='管理员备注'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='净金额'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='提供商参考号'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='payments.transaction', verbose_name='交易'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_account',
            field=models.CharField(max_length=100, verbose_name='提现账户'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_transfer', '银行转账')], db_index=True, max_length=20, verbose_name='提现方式'),
        ),
    ]
