# Generated by Django 5.2.7 on 2025-11-03 01:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.AlterModelOptions(
            name='gigextra',
            options={'ordering': ['price'], 'verbose_name': '服务附加项', 'verbose_name_plural': '服务附加项'},
        ),
        migrations.AlterModelOptions(
            name='gigfaq',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '服务常见问题', 'verbose_name_plural': '服务常见问题'},
        ),
        migrations.AlterModelOptions(
            name='gigfavorite',
            options={'verbose_name': '服务收藏', 'verbose_name_plural': '服务收藏'},
        ),
        migrations.AlterModelOptions(
            name='gigpackage',
            options={'ordering': ['price'], 'verbose_name': '服务套餐', 'verbose_name_plural': '服务套餐'},
        ),
        migrations.AlterModelOptions(
            name='gigreport',
            options={'verbose_name': '服务报告', 'verbose_name_plural': '服务报告'},
        ),
        migrations.AlterModelOptions(
            name='gigrequirement',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '服务需求', 'verbose_name_plural': '服务需求'},
        ),
        migrations.AlterModelOptions(
            name='gigsearchhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '服务搜索历史', 'verbose_name_plural': '服务搜索历史'},
        ),
        migrations.AlterModelOptions(
            name='gigstat',
            options={'ordering': ['-date'], 'verbose_name': '服务统计', 'verbose_name_plural': '服务统计'},
        ),
        migrations.AlterModelOptions(
            name='gigview',
            options={'verbose_name': '服务浏览记录', 'verbose_name_plural': '服务浏览记录'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gigs.category', verbose_name='父分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gigs', to='gigs.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='favorite_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='收藏次数'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='freelancer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'freelancer'}, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL, verbose_name='自由职业者'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, verbose_name='画廊图片'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否高级'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO描述'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='order_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='订单次数'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评价次数'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='searchable_text',
            field=models.TextField(db_index=True, verbose_name='搜索文本'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('paused', '暂停'), ('rejected', '被拒绝'), ('suspended', '被暂停')], db_index=True, default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='tags',
            field=models.TextField(help_text='搜索用逗号分隔的标签', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gigs/thumbnails/', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='gigextra',
            name='delivery_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='交付天数'),
        ),
        migrations.AlterField(
            model_name='gigextra',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gigextra',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigextra',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='gigextra',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='gigfaq',
            name='answer',
            field=models.TextField(verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='gigfaq',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigfaq',
            name='question',
            field=models.TextField(verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='gigfaq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='gigfavorite',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_gigs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='delivery_days',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='交付天数'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='功能特点'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='package_type',
            field=models.CharField(choices=[('basic', '基础'), ('standard', '标准'), ('premium', '高级')], db_index=True, max_length=20, verbose_name='套餐类型'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='revisions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='修改次数'),
        ),
        migrations.AlterField(
            model_name='gigpackage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='管理员备注'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='reason',
            field=models.CharField(choices=[('spam', '垃圾或误导内容'), ('inappropriate', '不当内容'), ('copyright', '版权侵犯'), ('fraud', '欺诈或骗局'), ('other', '其他')], max_length=50, verbose_name='举报原因'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_gigs', to=settings.AUTH_USER_MODEL, verbose_name='举报者'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gig_reports', to=settings.AUTH_USER_MODEL, verbose_name='审核者'),
        ),
        migrations.AlterField(
            model_name='gigreport',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('reviewed', '已审核'), ('resolved', '已解决'), ('dismissed', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='input_type',
            field=models.CharField(choices=[('text', '文本'), ('textarea', '多行文本'), ('file', '文件'), ('checkbox', '复选框'), ('number', '数字')], default='text', max_length=20, verbose_name='输入类型'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='是否必需'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='requirement_text',
            field=models.TextField(verbose_name='需求文本'),
        ),
        migrations.AlterField(
            model_name='gigrequirement',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='gigsearchhistory',
            name='filters_applied',
            field=models.JSONField(blank=True, default=dict, verbose_name='应用的筛选'),
        ),
        migrations.AlterField(
            model_name='gigsearchhistory',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='gigsearchhistory',
            name='query',
            field=models.CharField(db_index=True, max_length=200, verbose_name='搜索查询'),
        ),
        migrations.AlterField(
            model_name='gigsearchhistory',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='结果数量'),
        ),
        migrations.AlterField(
            model_name='gigsearchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='orders',
            field=models.PositiveIntegerField(default=0, verbose_name='订单数'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='收入'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='unique_views',
            field=models.PositiveIntegerField(default=0, verbose_name='独立浏览次数'),
        ),
        migrations.AlterField(
            model_name='gigstat',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='gigview',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='gigs.gig', verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='gigview',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='gigview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='gigview',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='用户代理'),
        ),
    ]
