# Generated by Django 5.2.7 on 2025-10-29 10:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_requirements', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('freelancer_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('requirements_provided', 'Requirements Provided'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('standard', 'Standard'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='standard', max_length=20)),
                ('delivery_deadline', models.DateTimeField(db_index=True)),
                ('estimated_delivery', models.DateTimeField(db_index=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(choices=[('platform', 'Platform Messaging'), ('email', 'Email'), ('wechat', 'WeChat')], default='platform', max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(limit_choices_to={'user_type': 'freelancer'}, on_delete=django.db.models.deletion.PROTECT, related_name='freelancer_orders', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gigs.gig')),
                ('gig_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gigs.gigpackage')),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('is_final_delivery', models.BooleanField(db_index=True, default=False)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('previous_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
            options={
                'db_table': 'orders_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('client_request', 'Client Request'), ('freelancer_request', 'Freelancer Request'), ('mutual_agreement', 'Mutual Agreement'), ('platform_intervention', 'Platform Intervention'), ('fraud', 'Fraud'), ('other', 'Other')], db_index=True, max_length=50)),
                ('detailed_reason', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('refund_reason', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_details', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order_cancellation',
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('delivery', 'Delivery Issues'), ('quality', 'Quality Issues'), ('communication', 'Communication Issues'), ('payment', 'Payment Issues'), ('other', 'Other Issues')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order_dispute',
            },
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gig_extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gigs.gigextra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_extras', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_extra',
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('delivery', 'Delivery'), ('system', 'System')], db_index=True, default='text', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_text', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('is_provided', models.BooleanField(db_index=True, default=False)),
                ('provided_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_requirement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_review_submitted', models.BooleanField(db_index=True, default=False)),
                ('freelancer_review_submitted', models.BooleanField(db_index=True, default=False)),
                ('review_deadline', models.DateTimeField(db_index=True)),
                ('reminder_sent', models.BooleanField(db_index=True, default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_request', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_review',
            },
        ),
        migrations.CreateModel(
            name='OrderStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('refunded_orders', models.PositiveIntegerField(default=0)),
                ('disputed_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_completion_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'orders_order_stat',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='orders_orde_date_98609e_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['freelancer', 'status'], name='orders_orde_freelan_324cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['gig', 'status'], name='orders_orde_gig_id_1cbe34_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_deadline'], name='orders_orde_deliver_7f3f03_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estimated_delivery'], name='orders_orde_estimat_ddb854_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_price'], name='orders_orde_total_p_aa9c17_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='orders_orde_priorit_b622f0_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'is_final_delivery'], name='orders_deli_order_i_2b902f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'is_accepted'], name='orders_deli_order_i_e093fa_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['created_at'], name='orders_deli_created_1a3ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercancellation',
            index=models.Index(fields=['order'], name='orders_orde_order_i_8b6fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercancellation',
            index=models.Index(fields=['cancelled_by'], name='orders_orde_cancell_391562_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercancellation',
            index=models.Index(fields=['reason'], name='orders_orde_reason_5c7a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercancellation',
            index=models.Index(fields=['is_processed'], name='orders_orde_is_proc_9de69b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['order'], name='orders_orde_order_i_bfae9a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['raised_by'], name='orders_orde_raised__5b85bf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['status'], name='orders_orde_status_1fe71c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['dispute_type', 'status'], name='orders_orde_dispute_1350a8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderextra',
            index=models.Index(fields=['order'], name='orders_orde_order_i_234a75_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_8228a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['sender'], name='orders_orde_sender__a0f60b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['message_type'], name='orders_orde_message_d5001c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['is_read'], name='orders_orde_is_read_f5df14_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequirement',
            index=models.Index(fields=['order', 'is_provided'], name='orders_orde_order_i_c92a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['order'], name='orders_orde_order_i_26d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['client_review_submitted'], name='orders_orde_client__6e57b3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['freelancer_review_submitted'], name='orders_orde_freelan_58ae5e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['review_deadline'], name='orders_orde_review__b452be_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_332edf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['new_status', 'created_at'], name='orders_orde_new_sta_c27ce3_idx'),
        ),
    ]
