# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at'], 'verbose_name': '交付', 'verbose_name_plural': '交付'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='ordercancellation',
            options={'verbose_name': '订单取消', 'verbose_name_plural': '订单取消'},
        ),
        migrations.AlterModelOptions(
            name='orderdispute',
            options={'verbose_name': '订单纠纷', 'verbose_name_plural': '订单纠纷'},
        ),
        migrations.AlterModelOptions(
            name='orderextra',
            options={'verbose_name': '订单附加项', 'verbose_name_plural': '订单附加项'},
        ),
        migrations.AlterModelOptions(
            name='ordermessage',
            options={'ordering': ['created_at'], 'verbose_name': '订单消息', 'verbose_name_plural': '订单消息'},
        ),
        migrations.AlterModelOptions(
            name='orderrequirement',
            options={'ordering': ['created_at'], 'verbose_name': '订单需求', 'verbose_name_plural': '订单需求'},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'verbose_name': '订单评价邀请', 'verbose_name_plural': '订单评价邀请'},
        ),
        migrations.AlterModelOptions(
            name='orderstat',
            options={'ordering': ['-date'], 'verbose_name': '订单统计', 'verbose_name_plural': '订单统计'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': '订单状态历史', 'verbose_name_plural': '订单状态历史'},
        ),
    ]
