# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '评价', 'verbose_name_plural': '评价'},
        ),
        migrations.AlterModelOptions(
            name='reviewhelpful',
            options={'verbose_name': '评价有用', 'verbose_name_plural': '评价有用'},
        ),
        migrations.AlterModelOptions(
            name='reviewinvitation',
            options={'verbose_name': '评价邀请', 'verbose_name_plural': '评价邀请'},
        ),
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'verbose_name': '评价报告', 'verbose_name_plural': '评价报告'},
        ),
        migrations.AlterModelOptions(
            name='reviewstat',
            options={'ordering': ['-date'], 'verbose_name': '评价统计', 'verbose_name_plural': '评价统计'},
        ),
        migrations.AlterModelOptions(
            name='reviewtemplate',
            options={'verbose_name': '评价模板', 'verbose_name_plural': '评价模板'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': '用户评分', 'verbose_name_plural': '用户评分'},
        ),
    ]
