# Generated by Django 5.2.7 on 2025-11-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'verbose_name': '拉黑用户', 'verbose_name_plural': '拉黑用户'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': '对话', 'verbose_name_plural': '对话'},
        ),
        migrations.AlterModelOptions(
            name='conversationtag',
            options={'verbose_name': '对话标签', 'verbose_name_plural': '对话标签'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': '消息附件', 'verbose_name_plural': '消息附件'},
        ),
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'verbose_name': '消息表情回应', 'verbose_name_plural': '消息表情回应'},
        ),
        migrations.AlterModelOptions(
            name='messagereport',
            options={'verbose_name': '消息报告', 'verbose_name_plural': '消息报告'},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'verbose_name': '消息模板', 'verbose_name_plural': '消息模板'},
        ),
        migrations.AlterModelOptions(
            name='messagingstat',
            options={'ordering': ['-date'], 'verbose_name': '消息统计', 'verbose_name_plural': '消息统计'},
        ),
    ]
